unit MyOtazka;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
  ExtCtrls, StdCtrls, Buttons;

type
  TFormMyOtazka = class(TForm)
    BitBtn1: TBitBtn;
    BitBtn2: TBitBtn;
    Image1: TImage;
    StaticText1: TMemo;
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  FormMyOtazka: TFormMyOtazka;

implementation

{$R *.DFM}


end.
